"""Generate `docs/catalog.md` from config + state.

It is generated, never hand-maintained, because a hand-written catalog is a second
source of truth that diverges the first time someone adds a variant. The spec's own
§15 was hand-written and nine of its endpoints were wrong.

No clock, no network: a build timestamp here would produce a non-empty commit every
day and destroy the guarantee that a diff means a real release.
"""

from __future__ import annotations

from pathlib import Path

from .models import Source
from .state import State

HEADER = """# Source catalog

Generated by `distro-iso-feed-refresh`. Do not edit by hand — edit `config/sources.yaml`.

| Distro | Variant | Strategy | Verify | Current version | Last seen |
|---|---|---|---|---|---|
"""


def render(sources: list[Source], state: State, path: Path) -> None:
    rows: list[str] = []
    for source in sorted(sources, key=lambda s: s.name):
        for variant in sorted(source.variants, key=lambda v: v.name):
            record = state.records.get(variant.key)
            version = record.version if record else "—"
            seen = record.seen if record else "—"
            verify = record.release.verify if record else "—"
            mirror = " ᴹ" if variant.mirror else ""
            rows.append(
                f"| {source.name}{mirror} | {variant.name} | {variant.strategy} "
                f"| {verify} | {version} | {seen} |"
            )

    body = HEADER + "\n".join(rows) + "\n"
    body += "\nᴹ = resolved via a mirror; no first-party endpoint publishes what we need.\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
